package hook

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const openCodePluginFile = "numbat.ts"

const openCodePluginMarker = "// numbat-managed plugin - do not edit"

var openCodeHookLifecycles = []Lifecycle{
	LifecycleOpenCodePreTool,
	LifecycleOpenCodePostTool,
	LifecyclePromptSubmit,
	LifecycleAssistant,
	LifecycleSessionStart,
	LifecycleSessionEnd,
}

// OpenCodePluginPath returns the user plugin path. OPENCODE_CONFIG_DIR names the
// config directory directly; otherwise the XDG config root contains opencode/.
func OpenCodePluginPath(home string) string {
	if root := os.Getenv("OPENCODE_CONFIG_DIR"); root != "" {
		return filepath.Join(root, "plugins", openCodePluginFile)
	}
	root := os.Getenv("XDG_CONFIG_HOME")
	if root == "" {
		root = filepath.Join(home, ".config")
	}
	return filepath.Join(root, "opencode", "plugins", openCodePluginFile)
}

// openCodePluginSourceWithArgs renders a dependency-free, observe-only plugin.
func openCodePluginSourceWithArgs(binary string, runtimeArgs []string) string {
	bin := jsString(binary)

	extra := []string{numbatHookMarker}
	extra = append(extra, runtimeArgs...)

	var b strings.Builder
	b.WriteString(openCodePluginMarker + "\n")
	b.WriteString("// Generated by `numbat hook install --agent opencode`; observe-only.\n")
	b.WriteString("import { spawn } from \"node:child_process\";\n\n")
	b.WriteString("const NUMBAT_BIN = " + bin + ";\n")
	b.WriteString("const EXTRA_ARGS = " + jsArgs(extra) + ";\n")
	b.WriteString("const INCLUDE_REASONING = EXTRA_ARGS.includes(\"--include-reasoning\");\n\n")
	b.WriteString(`const MAX_CONTEXTS = 4096;
const MAX_ACTIVE_MESSAGES = 256;
const SESSION_CONTEXT = new Map();
const ASSISTANT_PARTS = new Map();
const COMPLETED_MESSAGES = new Set();

function setBounded(map, key, value) {
  if (!map.has(key) && map.size >= MAX_CONTEXTS) {
    map.delete(map.keys().next().value);
  }
  map.set(key, value);
}

function mergeSession(sessionID, patch) {
  if (!sessionID) return;
  const next = { ...(SESSION_CONTEXT.get(sessionID) || {}) };
  for (const [key, value] of Object.entries(patch || {})) {
    if (value !== undefined && value !== null && value !== "") next[key] = value;
  }
  setBounded(SESSION_CONTEXT, sessionID, next);
}

function rememberSession(info) {
  if (!info?.id) return;
  mergeSession(info.id, {
    cwd: info.directory,
    subAgent: info.agent,
    model: info.model?.id,
    modelProvider: info.model?.providerID,
  });
}

function withSession(sessionID, payload, fallbackCwd) {
  return { cwd: fallbackCwd, ...(SESSION_CONTEXT.get(sessionID) || {}), ...payload };
}

function rememberCompleted(messageID) {
  if (!messageID || COMPLETED_MESSAGES.has(messageID)) return false;
  if (COMPLETED_MESSAGES.size >= MAX_CONTEXTS) {
    COMPLETED_MESSAGES.delete(COMPLETED_MESSAGES.values().next().value);
  }
  COMPLETED_MESSAGES.add(messageID);
  return true;
}

function rememberAssistant(message) {
  if (!message?.id || ASSISTANT_PARTS.has(message.id)) return;
  if (ASSISTANT_PARTS.size >= MAX_ACTIVE_MESSAGES) {
    ASSISTANT_PARTS.delete(ASSISTANT_PARTS.keys().next().value);
  }
  ASSISTANT_PARTS.set(message.id, { sessionID: message.sessionID, parts: new Map() });
}

function rememberMessagePart(part) {
  const parts = ASSISTANT_PARTS.get(part?.messageID)?.parts;
  if (!part?.id || !parts || !part.time?.end) return;
  const isText = part.type === "text" && !part.synthetic && !part.ignored;
  const isReasoning = INCLUDE_REASONING && part.type === "reasoning";
  if ((!isText && !isReasoning) || typeof part.text !== "string" || !part.text) return;
  parts.set(part.id, { type: part.type, text: part.text });
}

function takeMessageParts(messageID) {
  const parts = Array.from(ASSISTANT_PARTS.get(messageID)?.parts?.entries() || [])
    .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)
    .map(([, part]) => part);
  ASSISTANT_PARTS.delete(messageID);
  return parts;
}

function forgetMessage(messageID) {
  ASSISTANT_PARTS.delete(messageID);
}

function forgetMessagePart(input) {
  ASSISTANT_PARTS.get(input?.messageID)?.parts?.delete(input?.partID);
}

function forgetSession(sessionID) {
  for (const [messageID, state] of ASSISTANT_PARTS) {
    if (state.sessionID === sessionID) ASSISTANT_PARTS.delete(messageID);
  }
}

function promptText(parts) {
  return (parts || [])
    .filter((part) => part?.type === "text" && !part.synthetic && !part.ignored)
    .map((part) => part.text || "")
    .join("\n");
}

`)
	b.WriteString(`function forward(lifecycle, payload) {
  try {
    const body = { timestamp: new Date().toISOString(), ...payload };
    const child = spawn(NUMBAT_BIN, ["hook", lifecycle, "--agent", "opencode", ...EXTRA_ARGS], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
    });
    child.on("error", () => {});
    try {
      child.stdin.on("error", () => {});
      child.stdin.write(JSON.stringify(body));
      child.stdin.end();
    } catch (_) {}
    child.unref();
  } catch (_) {}
}

export const NumbatPlugin = async ({ directory }) => {
  return {
    "chat.message": async (input, output) => {
      if (!input?.sessionID) return;
      mergeSession(input.sessionID, {
        subAgent: input.agent,
        model: input.model?.modelID,
        modelProvider: input.model?.providerID,
      });
      forward("prompt-submit", withSession(input.sessionID, {
        sessionID: input.sessionID,
        prompt: promptText(output?.parts),
      }, directory));
    },
    "chat.params": async (input) => {
      if (!input?.sessionID) return;
      mergeSession(input.sessionID, {
        subAgent: input.agent,
        model: input.model?.id,
        modelProvider: input.model?.providerID,
      });
    },
    "tool.execute.before": async (input, output) => {
      forward("opencode-pre-tool", withSession(input?.sessionID, {
        tool: input?.tool,
        sessionID: input?.sessionID,
        callID: input?.callID,
        args: output?.args,
      }, directory));
    },
    "tool.execute.after": async (input, output) => {
      forward("opencode-post-tool", withSession(input?.sessionID, {
        tool: input?.tool,
        sessionID: input?.sessionID,
        callID: input?.callID,
        args: input?.args,
        metadata: output?.metadata,
      }, directory));
    },
    event: async ({ event }) => {
      if (event?.type === "session.created") {
        const info = event?.properties?.info;
        rememberSession(info);
        forward("session-start", withSession(info?.id, { sessionID: info?.id }, directory));
      } else if (event?.type === "session.deleted") {
        const info = event?.properties?.info;
        forward("session-end", withSession(info?.id, { sessionID: info?.id }, directory));
        SESSION_CONTEXT.delete(info?.id);
        forgetSession(info?.id);
      } else if (event?.type === "message.updated") {
        const info = event?.properties?.info;
        if (info?.role !== "assistant" || info?.summary) return;
        if (!info?.time?.completed) {
          rememberAssistant(info);
          return;
        }
        if (!rememberCompleted(info.id)) return;
        rememberAssistant(info);
        mergeSession(info.sessionID, {
          cwd: info.path?.cwd,
          subAgent: info.agent,
          model: info.modelID,
          modelProvider: info.providerID,
        });
        forward("assistant", withSession(info.sessionID, {
          sessionID: info.sessionID,
          timestamp: info.time.completed,
          message_parts: takeMessageParts(info.id),
        }, directory));
      } else if (event?.type === "message.part.updated") {
        rememberMessagePart(event?.properties?.part);
      } else if (event?.type === "message.part.removed") {
        forgetMessagePart(event?.properties);
      } else if (event?.type === "message.removed") {
        forgetMessage(event?.properties?.messageID);
      }
    },
  };
};

export default NumbatPlugin;
`)
	return b.String()
}

// jsString renders s as a JavaScript-compatible JSON string literal. JSON
// escaping covers every control character plus U+2028/U+2029, which is safer
// than maintaining a partial hand-written escape table for generated plugins.
func jsString(s string) string {
	data, _ := json.Marshal(s) // strings are always JSON-marshalable
	return string(data)
}

// jsArgs renders a string slice as a JavaScript array literal of quoted strings.
func jsArgs(args []string) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = jsString(a)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// isNumbatOpenCodePlugin reports whether the file at path is a numbat-owned
// OpenCode plugin, detected by the in-file marker (not merely the filename) so a
// numbat plugin is recognized regardless of how it was named. A missing or
// unreadable file is not numbat's.
func isNumbatOpenCodePlugin(path string) bool {
	_, owned, err := textHookFileOwnership(path, openCodePluginMarker)
	return err == nil && owned
}

// installOpenCodeWithArgs generates numbat's OpenCode plugin file and drops it at path. It
// is idempotent (a re-install rewrites the same stable file), backs up a pristine
// pre-existing numbat-owned file once before overwriting, and writes atomically
// 0600. It takes no enforce flag: OpenCode is observe-only (enforce refused at the
// Install gate). Unrelated files in the plugins directory are never touched.
func installOpenCodeWithArgs(path, binary string, runtimeArgs []string) (InstallReport, error) {
	rep := InstallReport{Agent: AgentOpenCode, SettingsPath: path, Supported: true}
	// Installer safety: never clobber a foreign file at the install path. If a file
	// already exists there and is NOT numbat-owned (no marker), refuse rather than
	// overwrite — a user's own numbat.ts (or any unrelated file dropped at this
	// path) must be left untouched, matching the uninstall path's same discipline.
	exists, owned, err := textHookFileOwnership(path, openCodePluginMarker)
	if err != nil {
		return rep, err
	}
	if exists && !owned {
		return rep, fmt.Errorf("refusing to overwrite existing non-numbat file at %s", path)
	}
	// Back up a pristine pre-existing numbat plugin once before overwriting.
	backup, err := backupIfExists(path)
	if err != nil {
		return rep, err
	}
	rep.BackupPath = backup
	if err := writeFileAtomic(path, []byte(openCodePluginSourceWithArgs(binary, runtimeArgs))); err != nil {
		return rep, err
	}
	rep.Installed = true
	rep.Changed = true
	rep.Message = "installed numbat plugin (observe-only; opencode never enforces)"
	return rep, nil
}

// uninstallOpenCode removes numbat's OpenCode plugin file, leaving every other
// plugin/file in the directory untouched. A missing file, or a file at this path
// that is NOT numbat's, is a no-op (Changed=false) — uninstall removes only what
// numbat installed.
func uninstallOpenCode(path string) (InstallReport, error) {
	rep := InstallReport{Agent: AgentOpenCode, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, openCodePluginMarker)
	if err != nil {
		return rep, err
	}
	if !exists {
		rep.Message = "no plugin file; nothing to remove"
		return rep, nil
	}
	if !owned {
		rep.Message = "plugin file is not numbat-owned; leaving it untouched"
		return rep, nil
	}
	if err := os.Remove(path); err != nil {
		return rep, err
	}
	rep.Changed = true
	rep.Message = "removed numbat plugin"
	return rep, nil
}

// statusOpenCode reports whether numbat's OpenCode plugin is installed, without
// modifying anything. OpenCode is observe-only, so an installed plugin is always
// observe-only.
func statusOpenCode(path string) InstallReport {
	rep := InstallReport{Agent: AgentOpenCode, SettingsPath: path, Supported: true}
	rep.Installed = isNumbatOpenCodePlugin(path)
	if rep.Installed {
		rep.Message = "numbat plugin installed (observe-only)"
	} else {
		rep.Message = "numbat plugin not installed"
	}
	return rep
}

// OpenCodeLifecycleArgs returns the lifecycle argument names numbat wires into the
// OpenCode plugin, as strings, for diagnostics and the parity test.
func OpenCodeLifecycleArgs() []string {
	out := make([]string, 0, len(openCodeHookLifecycles))
	for _, lc := range openCodeHookLifecycles {
		out = append(out, string(lc))
	}
	return out
}
