package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	ampPluginFile   = "numbat.ts"
	ampPluginMarker = "// numbat-managed Amp plugin - do not edit"
)

func AmpPluginPath(home string) string {
	return filepath.Join(home, ".config", "amp", "plugins", ampPluginFile)
}

func ampPluginSourceWithArgs(binary string, runtimeArgs []string, enforce bool) string {
	extra := []string{numbatHookMarker}
	extra = append(extra, runtimeArgs...)
	if enforce {
		extra = append(extra, "--enforce")
	}
	var b strings.Builder
	b.WriteString(ampPluginMarker + "\n")
	b.WriteString("// Generated by `numbat hook install --agent amp`; failures always allow.\n")
	b.WriteString("import { spawn, spawnSync } from \"node:child_process\";\n")
	b.WriteString("import type { PluginAPI } from \"@ampcode/plugin\";\n\n")
	b.WriteString("const NUMBAT_BIN = " + jsString(binary) + ";\n")
	b.WriteString("const EXTRA_ARGS = " + jsArgs(extra) + ";\n")
	b.WriteString("const ENFORCE = " + fmt.Sprintf("%t", enforce) + ";\n\n")
	b.WriteString(`function forward(lifecycle, payload) {
  try {
    const child = spawn(NUMBAT_BIN, ["hook", lifecycle, "--agent", "amp", ...EXTRA_ARGS], {
      stdio: ["pipe", "ignore", "ignore"], detached: true,
    });
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify({ timestamp: new Date().toISOString(), ...payload }));
    child.unref();
  } catch (_) {}
}

function finalAssistantText(messages) {
  if (!Array.isArray(messages)) return "";
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i];
    if (message?.role !== "assistant" || !Array.isArray(message.content)) continue;
    return message.content
      .filter((block) => block?.type === "text" && typeof block.text === "string")
      .map((block) => block.text)
      .join("\n");
  }
  return "";
}

function toolResultMetadata(output) {
  if (!output || typeof output !== "object" || Array.isArray(output)) return undefined;
  return typeof output.exitCode === "number" ? { exitCode: output.exitCode } : undefined;
}

function preTool(payload) {
  if (!ENFORCE) {
    forward("pre-tool", payload);
    return { action: "allow" };
  }
  try {
    const result = spawnSync(NUMBAT_BIN, ["hook", "pre-tool", "--agent", "amp", ...EXTRA_ARGS], {
      input: JSON.stringify({ timestamp: new Date().toISOString(), ...payload }),
      encoding: "utf8", timeout: 9000, maxBuffer: 1024 * 1024,
    });
    if (result.error || result.status !== 0 || !result.stdout) return { action: "allow" };
    const response = JSON.parse(result.stdout);
    if (response?.action === "reject-and-continue" && typeof response.message === "string") return response;
  } catch (_) {}
  return { action: "allow" };
}

export default function (amp: PluginAPI) {
  const root = amp.system.workspaceRoot;
  const cwd = root ? amp.helpers.filePathFromURI(root) : undefined;
  amp.on("session.start", async (event) => {
    forward("session-start", { session_id: event.thread.id, cwd });
  });
  amp.on("agent.start", async (event) => {
    forward("prompt-submit", { session_id: event.thread.id, cwd, prompt: event.message });
  });
  amp.on("tool.call", async (event) => preTool({
    session_id: event.thread.id, cwd, tool_call_id: event.toolUseID,
    tool_name: event.tool, tool_input: event.input,
  }));
  amp.on("tool.result", async (event) => {
    forward("post-tool", {
      session_id: event.thread.id, cwd, tool_call_id: event.toolUseID,
      tool_name: event.tool, tool_input: event.input, tool_result: toolResultMetadata(event.output), tool_response: event.output,
      status: event.status, error: event.error,
    });
  });
  amp.on("agent.end", async (event) => {
    forward("assistant", {
      session_id: event.thread.id, cwd, assistant_text: finalAssistantText(event.messages),
    });
  });
}
`)
	return b.String()
}

func isNumbatAmpPlugin(path string) bool {
	_, owned, err := textHookFileOwnership(path, ampPluginMarker)
	return err == nil && owned
}

func installAmpWithArgs(path, binary string, runtimeArgs []string, enforce bool) (InstallReport, error) {
	rep := InstallReport{Agent: AgentAmp, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, ampPluginMarker)
	if err != nil {
		return rep, err
	}
	if exists && !owned {
		return rep, fmt.Errorf("refusing to overwrite existing non-numbat file at %s", path)
	}
	backup, err := backupIfExists(path)
	if err != nil {
		return rep, err
	}
	rep.BackupPath = backup
	if err := writeFileAtomic(path, []byte(ampPluginSourceWithArgs(binary, runtimeArgs, enforce))); err != nil {
		return rep, err
	}
	rep.Installed, rep.Changed = true, true
	rep.Message = "installed numbat Amp plugin (reload plugins in Amp)"
	if enforce {
		rep.Message = "installed numbat Amp plugin (enforce mode; reload plugins in Amp)"
	}
	return rep, nil
}

func uninstallAmp(path string) (InstallReport, error) {
	rep := InstallReport{Agent: AgentAmp, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, ampPluginMarker)
	if err != nil {
		return rep, err
	}
	if !exists {
		rep.Message = "no plugin file; nothing to remove"
		return rep, nil
	}
	if !owned {
		rep.Message = "plugin file is not numbat-owned; leaving it untouched"
		return rep, nil
	}
	if err := os.Remove(path); err != nil {
		return rep, err
	}
	rep.Changed, rep.Message = true, "removed numbat Amp plugin"
	return rep, nil
}

func statusAmp(path string) InstallReport {
	rep := InstallReport{Agent: AgentAmp, SettingsPath: path, Supported: true, Installed: isNumbatAmpPlugin(path)}
	if rep.Installed {
		rep.Message = "numbat Amp plugin installed"
	} else {
		rep.Message = "numbat Amp plugin not installed"
	}
	return rep
}
