package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	kiloPluginFile   = "numbat.ts"
	kiloPluginMarker = "// numbat-managed Kilo plugin - do not edit"
)

// KiloPluginPath returns the current CLI and VS Code extension's global
// auto-discovered plugin path.
func KiloPluginPath(home string) string {
	root := os.Getenv("XDG_CONFIG_HOME")
	if root == "" {
		root = filepath.Join(home, ".config")
	}
	return filepath.Join(root, "kilo", "plugin", kiloPluginFile)
}

func kiloPluginSourceWithArgs(binary string, runtimeArgs []string, enforce bool) string {
	extra := []string{numbatHookMarker}
	extra = append(extra, runtimeArgs...)
	if enforce {
		extra = append(extra, "--enforce")
	}
	var b strings.Builder
	b.WriteString(kiloPluginMarker + "\n")
	b.WriteString("// Generated by `numbat hook install --agent kilo`; failures always allow.\n")
	b.WriteString("import { spawn, spawnSync } from \"node:child_process\";\n")
	b.WriteString("import type { Plugin } from \"@kilocode/plugin\";\n\n")
	b.WriteString("const NUMBAT_BIN = " + jsString(binary) + ";\n")
	b.WriteString("const EXTRA_ARGS = " + jsArgs(extra) + ";\n")
	b.WriteString("const ENFORCE = " + fmt.Sprintf("%t", enforce) + ";\n")
	b.WriteString("const INCLUDE_REASONING = EXTRA_ARGS.includes(\"--include-reasoning\");\n\n")
	b.WriteString(`const MAX_CONTEXTS = 4096;
const MAX_ACTIVE_MESSAGES = 256;
const ASSISTANT_PARTS = new Map();
const COMPLETED_MESSAGES = new Set();

function rememberBounded(set, key) {
  if (!key || set.has(key)) return false;
  if (set.size >= MAX_CONTEXTS) set.delete(set.values().next().value);
  set.add(key);
  return true;
}

function rememberAssistant(message) {
  if (!message?.id || ASSISTANT_PARTS.has(message.id)) return;
  if (ASSISTANT_PARTS.size >= MAX_ACTIVE_MESSAGES) {
    ASSISTANT_PARTS.delete(ASSISTANT_PARTS.keys().next().value);
  }
  ASSISTANT_PARTS.set(message.id, { sessionID: message.sessionID, parts: new Map() });
}

function rememberMessagePart(part) {
  const parts = ASSISTANT_PARTS.get(part?.messageID)?.parts;
  if (!part?.id || !parts || !part.time?.end) return;
  const isText = part.type === "text" && !part.synthetic && !part.ignored;
  const isReasoning = INCLUDE_REASONING && part.type === "reasoning";
  if ((!isText && !isReasoning) || typeof part.text !== "string" || !part.text) return;
  parts.set(part.id, { type: part.type, text: part.text });
}

function takeMessageParts(messageID) {
  const parts = Array.from(ASSISTANT_PARTS.get(messageID)?.parts?.entries() || [])
    .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)
    .map(([, part]) => part);
  ASSISTANT_PARTS.delete(messageID);
  return parts;
}

function forgetMessage(messageID) {
  ASSISTANT_PARTS.delete(messageID);
}

function forgetMessagePart(input) {
  ASSISTANT_PARTS.get(input?.messageID)?.parts?.delete(input?.partID);
}

function forgetSession(sessionID) {
  for (const [messageID, state] of ASSISTANT_PARTS) {
    if (state.sessionID === sessionID) ASSISTANT_PARTS.delete(messageID);
  }
}

function promptText(parts) {
  return (parts || [])
    .filter((part) => part?.type === "text" && !part.synthetic && !part.ignored)
    .map((part) => part.text || "")
    .join("\n");
}

function forward(lifecycle, payload) {
  try {
    const child = spawn(NUMBAT_BIN, ["hook", lifecycle, "--agent", "kilo", ...EXTRA_ARGS], {
      stdio: ["pipe", "ignore", "ignore"], detached: true,
    });
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify({ timestamp: new Date().toISOString(), ...payload }));
    child.unref();
  } catch (_) {}
}

function deniedReason(payload) {
  if (!ENFORCE) {
    forward("pre-tool", payload);
    return undefined;
  }
  try {
    const result = spawnSync(NUMBAT_BIN, ["hook", "pre-tool", "--agent", "kilo", ...EXTRA_ARGS], {
      input: JSON.stringify({ timestamp: new Date().toISOString(), ...payload }),
      encoding: "utf8", timeout: 9000, maxBuffer: 1024 * 1024,
    });
    if (result.error || result.status !== 0 || !result.stdout) return undefined;
    const response = JSON.parse(result.stdout);
    if (response?.block === true && typeof response.reason === "string") return response.reason;
  } catch (_) {}
  return undefined;
}

const server: Plugin = async ({ directory }) => ({
  "chat.message": async (input, output) => {
    forward("prompt-submit", {
      session_id: input?.sessionID, cwd: directory,
      sub_agent: input?.agent, prompt: promptText(output?.parts),
      model: input?.model?.modelID, model_provider: input?.model?.providerID,
    });
  },
  "tool.execute.before": async (input, output) => {
    const payload = {
      session_id: input?.sessionID, cwd: directory, tool_call_id: input?.callID,
      tool_name: input?.tool, tool_input: output?.args,
    };
    const reason = deniedReason(payload);
    if (reason) throw new Error(reason);
  },
  "tool.execute.after": async (input, output) => {
    forward("post-tool", {
      session_id: input?.sessionID, cwd: directory, tool_call_id: input?.callID,
      tool_name: input?.tool, tool_input: input?.args, metadata: output?.metadata,
    });
  },
  event: async ({ event }) => {
    const info = event?.properties?.info;
    if (event?.type === "session.created") {
      forward("session-start", { session_id: info?.id, cwd: info?.directory || directory });
    } else if (event?.type === "session.deleted") {
      forward("session-end", { session_id: info?.id, cwd: info?.directory || directory });
      forgetSession(info?.id);
    } else if (event?.type === "message.updated") {
      if (info?.role !== "assistant" || info?.summary) return;
      if (!info?.time?.completed) {
        rememberAssistant(info);
        return;
      }
      if (!rememberBounded(COMPLETED_MESSAGES, info.id)) return;
      rememberAssistant(info);
      forward("assistant", {
        session_id: info?.sessionID, cwd: info?.path?.cwd || directory,
        sub_agent: info?.agent, model: info?.modelID, model_provider: info?.providerID,
        timestamp: info?.time?.completed,
        message_parts: takeMessageParts(info.id),
      });
    } else if (event?.type === "message.part.updated") {
      rememberMessagePart(event?.properties?.part);
    } else if (event?.type === "message.part.removed") {
      forgetMessagePart(event?.properties);
    } else if (event?.type === "message.removed") {
      forgetMessage(event?.properties?.messageID);
    }
  },
});

export default { id: "numbat", server };
`)
	return b.String()
}

func isNumbatKiloPlugin(path string) bool {
	_, owned, err := textHookFileOwnership(path, kiloPluginMarker)
	return err == nil && owned
}

func installKiloWithArgs(path, binary string, runtimeArgs []string, enforce bool) (InstallReport, error) {
	rep := InstallReport{Agent: AgentKilo, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, kiloPluginMarker)
	if err != nil {
		return rep, err
	}
	if exists && !owned {
		return rep, fmt.Errorf("refusing to overwrite existing non-numbat Kilo plugin at %s", path)
	}
	backup, err := backupIfExists(path)
	if err != nil {
		return rep, err
	}
	rep.BackupPath = backup
	if err := writeFileAtomic(path, []byte(kiloPluginSourceWithArgs(binary, runtimeArgs, enforce))); err != nil {
		return rep, err
	}
	rep.Installed, rep.Changed = true, true
	rep.Message = "installed numbat Kilo plugin (restart or reload Kilo)"
	if enforce {
		rep.Message = "installed numbat Kilo plugin in enforce mode (restart or reload Kilo)"
	}
	return rep, nil
}

func uninstallKilo(path string) (InstallReport, error) {
	rep := InstallReport{Agent: AgentKilo, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, kiloPluginMarker)
	if err != nil {
		return rep, err
	}
	if !exists {
		rep.Message = "no Kilo plugin file; nothing to remove"
		return rep, nil
	}
	if !owned {
		rep.Message = "Kilo plugin file is not numbat-owned; leaving it untouched"
		return rep, nil
	}
	if err := os.Remove(path); err != nil {
		return rep, err
	}
	rep.Changed, rep.Message = true, "removed numbat Kilo plugin"
	return rep, nil
}

func statusKilo(path string) InstallReport {
	rep := InstallReport{Agent: AgentKilo, SettingsPath: path, Supported: true, Installed: isNumbatKiloPlugin(path)}
	if rep.Installed {
		rep.Message = "numbat Kilo plugin installed"
	} else {
		rep.Message = "numbat Kilo plugin not installed"
	}
	return rep
}
