package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	piPluginFile   = "numbat.ts"
	piPluginMarker = "// numbat-managed Pi extension - do not edit"
)

// PiExtensionPath returns the global extension path. PI_CODING_AGENT_DIR names
// the agent config directory directly and defaults to ~/.pi/agent.
func PiExtensionPath(home string) string {
	root := os.Getenv("PI_CODING_AGENT_DIR")
	if root == "" {
		root = filepath.Join(home, ".pi", "agent")
	}
	return filepath.Join(root, "extensions", piPluginFile)
}

func piPluginSourceWithArgs(binary string, runtimeArgs []string, enforce bool) string {
	extra := []string{numbatHookMarker}
	extra = append(extra, runtimeArgs...)
	if enforce {
		extra = append(extra, "--enforce")
	}
	var b strings.Builder
	b.WriteString(piPluginMarker + "\n")
	b.WriteString("// Generated by `numbat hook install --agent pi`; failures always allow.\n")
	b.WriteString("import { spawn, spawnSync } from \"node:child_process\";\n\n")
	b.WriteString("const NUMBAT_BIN = " + jsString(binary) + ";\n")
	b.WriteString("const EXTRA_ARGS = " + jsArgs(extra) + ";\n")
	b.WriteString("const ENFORCE = " + fmt.Sprintf("%t", enforce) + ";\n")
	b.WriteString("const INCLUDE_REASONING = EXTRA_ARGS.includes(\"--include-reasoning\");\n\n")
	b.WriteString(`function body(ctx, payload) {
  return {
    cwd: ctx?.cwd,
    session_id: ctx?.sessionManager?.getSessionId?.(),
    model: ctx?.model?.id,
    model_provider: ctx?.model?.provider,
    timestamp: new Date().toISOString(),
    ...payload,
  };
}

function forward(lifecycle, payload) {
  try {
    const child = spawn(NUMBAT_BIN, ["hook", lifecycle, "--agent", "pi", ...EXTRA_ARGS], {
      stdio: ["pipe", "ignore", "ignore"], detached: true,
    });
    child.on("error", () => {});
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
    child.unref();
  } catch (_) {}
}

function preTool(payload) {
  if (!ENFORCE) {
    forward("pre-tool", payload);
    return undefined;
  }
  try {
    const result = spawnSync(NUMBAT_BIN, ["hook", "pre-tool", "--agent", "pi", ...EXTRA_ARGS], {
      input: JSON.stringify(payload), encoding: "utf8", timeout: 9000, maxBuffer: 1024 * 1024,
    });
    if (result.error || result.status !== 0 || !result.stdout) return undefined;
    const response = JSON.parse(result.stdout);
    return response?.block === true ? response : undefined;
  } catch (_) {
    return undefined;
  }
}

export default function (pi) {
  pi.on("session_start", async (event, ctx) => {
    forward("session-start", body(ctx, { reason: event.reason }));
  });
  pi.on("before_agent_start", async (event, ctx) => {
    forward("prompt-submit", body(ctx, { prompt: event.prompt }));
  });
  pi.on("tool_call", async (event, ctx) => preTool(body(ctx, {
    tool_call_id: event.toolCallId, tool_name: event.toolName, tool_input: event.input,
  })));
  pi.on("tool_result", async (event, ctx) => {
    forward("post-tool", body(ctx, {
      tool_call_id: event.toolCallId, tool_name: event.toolName, tool_input: event.input,
      tool_result: event.details, is_error: event.isError,
    }));
  });
  pi.on("message_end", async (event, ctx) => {
    if (event.message.role !== "assistant") return;
    const message_parts = event.message.content.flatMap((block) => {
      if (block?.type === "text" && typeof block.text === "string" && block.text) {
        return [{ type: "text", text: block.text }];
      }
      if (INCLUDE_REASONING && block?.type === "thinking" && !block.redacted &&
          typeof block.thinking === "string" && block.thinking) {
        return [{ type: "reasoning", text: block.thinking }];
      }
      return [];
    });
    if (message_parts.length) forward("assistant", body(ctx, {
      model: event.message.responseModel ?? event.message.model,
      model_provider: event.message.provider,
      timestamp: event.message.timestamp,
      message_parts,
    }));
  });
  pi.on("session_shutdown", async (event, ctx) => {
    forward("session-end", body(ctx, { reason: event.reason }));
  });
}
`)
	return b.String()
}

func isNumbatPiPlugin(path string) bool {
	_, owned, err := textHookFileOwnership(path, piPluginMarker)
	return err == nil && owned
}

func installPiWithArgs(path, binary string, runtimeArgs []string, enforce bool) (InstallReport, error) {
	rep := InstallReport{Agent: AgentPi, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, piPluginMarker)
	if err != nil {
		return rep, err
	}
	if exists && !owned {
		return rep, fmt.Errorf("refusing to overwrite existing non-numbat file at %s", path)
	}
	backup, err := backupIfExists(path)
	if err != nil {
		return rep, err
	}
	rep.BackupPath = backup
	if err := writeFileAtomic(path, []byte(piPluginSourceWithArgs(binary, runtimeArgs, enforce))); err != nil {
		return rep, err
	}
	rep.Installed, rep.Changed = true, true
	rep.Message = "installed numbat Pi extension"
	if enforce {
		rep.Message += " (enforce mode: blocks tool_call matches from rules marked enforce=true)"
	}
	return rep, nil
}

func uninstallPi(path string) (InstallReport, error) {
	rep := InstallReport{Agent: AgentPi, SettingsPath: path, Supported: true}
	exists, owned, err := textHookFileOwnership(path, piPluginMarker)
	if err != nil {
		return rep, err
	}
	if !exists {
		rep.Message = "no extension file; nothing to remove"
		return rep, nil
	}
	if !owned {
		rep.Message = "extension file is not numbat-owned; leaving it untouched"
		return rep, nil
	}
	if err := os.Remove(path); err != nil {
		return rep, err
	}
	rep.Changed, rep.Message = true, "removed numbat Pi extension"
	return rep, nil
}

func statusPi(path string) InstallReport {
	rep := InstallReport{Agent: AgentPi, SettingsPath: path, Supported: true, Installed: isNumbatPiPlugin(path)}
	if rep.Installed {
		rep.Message = "numbat Pi extension installed"
	} else {
		rep.Message = "numbat Pi extension not installed"
	}
	return rep
}
