
eventequals
eventequals	
eventequalslogical_and
logical_or
shell_commands	
commandmatches_stringlists_range	
command	list_size
igreater_int64 logical_not!	
command#
list_slice%
i	(
arg)matches_string,	
@result-logical_not.not_strictly_false/	
@result0
logical_or1	
@result3logical_and4	
command6
index_list7
i8matches_string;lists_range<	
command>	list_sizeA
targetBgreater_int64C
iDlogical_notE	
commandG
index_listH
targetIstarts_with_stringKlogical_andLlogical_notM	
commandO
list_sliceP
iQ	add_int64S
target	V
argWmatches_stringZ	
@result[logical_not\not_strictly_false]	
@result^
logical_or_	
@resultalogical_andblogical_notc
targetdgreater_int64e
if	add_int64h	
commandj
index_listk
targetlsubtract_int64nmatches_stringplogical_andqlogical_ands	
@resulttlogical_notunot_strictly_falsev	
@resultw
logical_orx	
@resultzlogical_and{	
command}
index_list~
imatches_string	
commandƒmatches_string…logical_and‡lists_rangeˆ	
commandŠ	list_size
targetgreater_int64
ilogical_not‘	
command“
index_list”
target•starts_with_string—logical_and˜logical_not™	
command›
list_sliceœ
i	add_int64Ÿ
target
¢
arg£matches_string¦	
@result§logical_not¨not_strictly_false©	
@resultª
logical_or«	
@result­logical_and®logical_not¯
target°greater_int64±
i²	add_int64´	
command¶
index_list·
target¸subtract_int64ºmatches_string¼logical_and½logical_and¿	
@resultÀlogical_notÁnot_strictly_falseÂ	
@resultÃ
logical_orÄ	
@resultÆlogical_andÇ
logical_orÈ	
commandÊ
index_listË
iÌmatches_stringÏlists_rangeĞ	
commandÒ	list_sizeÕ
targetÖgreater_int64×
iØ	
commandÚ
index_listÛ
targetÜmatches_stringŞlogical_andßlogical_notà	
commandâ
list_sliceã
iä	add_int64æ
target
é
argêmatches_stringí	
@resultîlogical_notïnot_strictly_falseğ	
@resultñ
logical_orò	
@resultôlogical_andõlogical_notö
target÷greater_int64ø
iù	add_int64û	
commandı
index_listş
targetÿsubtract_int64matches_stringƒlogical_and„logical_and†	
@result‡logical_notˆnot_strictly_false‰	
@resultŠ
logical_or‹	
@resultlogical_and
logical_orlogical_and‘lists_range’
i•
j–equals˜	
commandš
index_list›
jœstarts_with_string
logical_orŸ
j greater_int64¢	
command¤
index_list¥
j¦subtract_int64¨matches_stringªlogical_and«
logical_or­	
@result®not_strictly_false¯	
@result°logical_and±	
@result³logical_andµ	
@result¶logical_not·not_strictly_false¸	
@result¹
logical_orº	
@result¼logical_and½	
command¿matches_stringÂlists_rangeÃ	
commandÅ	list_sizeÈ
iÉgreater_int64Ëlogical_notÌ	
commandÎ
list_sliceĞ
i
Ó
argÔmatches_string×	
@resultØlogical_notÙnot_strictly_falseÚ	
@resultÛ
logical_orÜ	
@resultŞlogical_andß	
commandá
index_listâ
iãmatches_stringålogical_andçlists_rangeè	
commandê	list_sizeí
targetîgreater_int64ï
iğlogical_notñ	
commandó
index_listô
targetõstarts_with_string÷logical_andølogical_notù	
commandû
list_sliceü
iı	add_int64ÿ
target
‚
argƒmatches_string†	
@result‡logical_notˆnot_strictly_false‰	
@resultŠ
logical_or‹	
@resultlogical_andlogical_not
targetgreater_int64‘
i’	add_int64”	
command–
index_list—
target˜subtract_int64šmatches_stringœlogical_andlogical_andŸ	
@result logical_not¡not_strictly_false¢	
@result£
logical_or¤	
@result¦logical_and¨lists_range©
i¬
j­equals¯	
command±
index_list²
j³starts_with_stringµ
logical_or¶
j·greater_int64¹	
command»
index_list¼
j½subtract_int64¿matches_stringÁlogical_andÂ
logical_orÄ	
@resultÅnot_strictly_falseÆ	
@resultÇlogical_andÈ	
@resultÊlogical_andÌ	
@resultÍlogical_notÎnot_strictly_falseÏ	
@resultĞ
logical_orÑ	
@resultÓlogical_andÔ
logical_orÕ	
command×matches_stringÚlists_rangeÛ	
commandİ	list_sizeŞsubtract_int64â
iãgreater_int64ålogical_notæ	
commandè
list_sliceê
i
í
argîmatches_stringñ	
@resultòlogical_notónot_strictly_falseô	
@resultõ
logical_orö	
@resultølogical_andù	
commandû
index_listü
iımatches_stringÿlogical_and€	
command‚
index_listƒ
i„	add_int64†matches_stringˆlogical_andŠlists_range‹	
command	list_size
target‘greater_int64’
i“	add_int64•logical_not–	
command˜
index_list™
targetšstarts_with_stringœlogical_andlogical_not	
command 
list_slice¡
i¢	add_int64¤
target
§
arg¨matches_string«	
@result¬logical_not­not_strictly_false®	
@result¯
logical_or°	
@result²logical_and³logical_not´
targetµgreater_int64¶
i·	add_int64¹	
command»
index_list¼
target½subtract_int64¿matches_stringÁlogical_andÂlogical_andÄ	
@resultÅlogical_notÆnot_strictly_falseÇ	
@resultÈ
logical_orÉ	
@resultËlogical_andÍlists_rangeÎ
iÑ
jÒequalsÔ	
commandÖ
index_list×
jØstarts_with_stringÚ
logical_orÛ
jÜgreater_int64Ş	
commandà
index_listá
jâsubtract_int64ämatches_stringælogical_andç
logical_oré	
@resultênot_strictly_falseë	
@resultìlogical_andí	
@resultïlogical_andñ	
@resultòlogical_notónot_strictly_falseô	
@resultõ
logical_orö	
@resultølogical_andù
logical_orú	
commandümatches_stringÿlists_range€	
command‚	list_size…
i†greater_int64ˆlogical_not‰	
command‹
list_slice
i

arg‘matches_string”	
@result•logical_not–not_strictly_false—	
@result˜
logical_or™	
@result›logical_andœ	
command
index_listŸ
i matches_string¢logical_and¤lists_range¥	
command§	list_sizeª
target«greater_int64¬
i­logical_not®	
command°
index_list±
target²starts_with_string´logical_andµlogical_not¶	
command¸
list_slice¹
iº	add_int64¼
target
¿
argÀmatches_stringÃ	
@resultÄlogical_notÅnot_strictly_falseÆ	
@resultÇ
logical_orÈ	
@resultÊlogical_andËlogical_notÌ
targetÍgreater_int64Î
iÏ	add_int64Ñ	
commandÓ
index_listÔ
targetÕsubtract_int64×matches_stringÙlogical_andÚlogical_andÜ	
@resultİlogical_notŞnot_strictly_falseß	
@resultà
logical_orá	
@resultãlogical_andålists_rangeæ
ié
jêequalsì	
commandî
index_listï
jğstarts_with_stringò
logical_oró
jôgreater_int64ö	
commandø
index_listù
júsubtract_int64ümatches_stringşlogical_andÿ
logical_or	
@result‚not_strictly_falseƒ	
@result„logical_and…	
@result‡logical_andˆ	
commandŠ
list_sliceŒ
i

argmatches_string“	
@result”logical_not•not_strictly_false–	
@result—
logical_or˜	
@result›lists_rangeœ
isubtract_int64¡	
command£
index_list¤
j¥matches_string§	
command©
index_listª
j«	add_int64­matches_string¯logical_and±	
@result²logical_not³not_strictly_false´	
@resultµ
logical_or¶	
@result¸
logical_or¹	
command½	
wrapper¿matches_stringÁ	
wrapper
Å
argÆmatches_stringÉ	
@resultÊlogical_notËnot_strictly_falseÌ	
@resultÍ
logical_orÎ	
@resultĞlogical_andÒ	
@resultÓlogical_notÔnot_strictly_falseÕ	
@resultÖ
logical_or×	
@resultÙ
logical_orÚ	
commandŞlogical_notß

assignmentá

assignmentãequalsålogical_andæ

assignmentèmatches_stringêlogical_andì	
@resultílogical_notînot_strictly_falseï	
@resultğ
logical_orñ	
@resultó
logical_orôlogical_andö	
@result÷logical_notønot_strictly_falseù	
@resultú
logical_orû	
@resultılogical_andş
logical_orÿ	
commandmatches_string„lists_range…	
command‡	list_sizeŠ
i‹greater_int64logical_not	
command
list_slice’
i
•
arg–matches_string™	
@resultšlogical_not›not_strictly_falseœ	
@result
logical_or	
@result logical_and¡	
command£
index_list¤
i¥matches_string§logical_and©lists_rangeª	
command¬	list_size¯
target°greater_int64±
i²logical_not³	
commandµ
index_list¶
target·starts_with_string¹logical_andºlogical_not»	
command½
list_slice¾
i¿	add_int64Á
target
Ä
argÅmatches_stringÈ	
@resultÉlogical_notÊnot_strictly_falseË	
@resultÌ
logical_orÍ	
@resultÏlogical_andĞlogical_notÑ
targetÒgreater_int64Ó
iÔ	add_int64Ö	
commandØ
index_listÙ
targetÚsubtract_int64Ümatches_stringŞlogical_andßlogical_andá	
@resultâlogical_notãnot_strictly_falseä	
@resultå
logical_oræ	
@resultèlogical_andêlists_rangeë
iî
jïequalsñ	
commandó
index_listô
jõstarts_with_string÷
logical_orø
jùgreater_int64û	
commandı
index_listş
jÿsubtract_int64matches_stringƒlogical_and„
logical_or†	
@result‡not_strictly_falseˆ	
@result‰logical_andŠ	
@resultŒlogical_and	
command
list_slice‘
i
”
arg•matches_string˜	
@result™logical_notšnot_strictly_false›	
@resultœ
logical_or	
@result lists_range¡
i¢subtract_int64¦	
command¨
index_list©
jªmatches_string¬	
command®
index_list¯
j°	add_int64²matches_string´logical_and¶	
@result·logical_not¸not_strictly_false¹	
@resultº
logical_or»	
@result½
logical_or¾logical_andÀ	
@resultÁlogical_notÂnot_strictly_falseÃ	
@resultÄ
logical_orÅ	
@resultÇlogical_andÈ
logical_orÊ	
@resultËlogical_notÌnot_strictly_falseÍ	
@resultÎ
logical_orÏ	
@resultÑlogical_and
:

 
 
:

 
 	
:

 

 2
Jrule.ShellCommandJrule.ShellCommand
2
Jrule.ShellCommand
2
 !Jrule.ShellCommand
"2

#2
$%()*+,-./01234Jrule.ShellCommand
52
6789
;2
<Jrule.ShellCommand
=2
>ABCDEJrule.ShellCommand
F2
GHIJKLMJrule.ShellCommand
N2

O2
PQRSVWXYZ[\]^_`abcdefghJrule.ShellCommand
i2
jklmnopqrstuvwxyz{Jrule.ShellCommand
|2
}~€Jrule.ShellCommand‚ƒ„…‡2
ˆJrule.ShellCommand‰2
Š‘Jrule.ShellCommand’2
“”•–—˜™Jrule.ShellCommandš2
›2
œŸ¢£¤¥¦§¨©ª«¬­®¯°±²³´Jrule.ShellCommandµ2
¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈJrule.ShellCommandÉ2
ÊËÌÍÏ2
ĞJrule.ShellCommandÑ2
ÒÕÖ×ØJrule.ShellCommandÙ2
ÚÛÜİŞßàJrule.ShellCommandá2
â2
ãäåæéêëìíîïğñòóôõö÷øùúûJrule.ShellCommandü2
ışÿ€‚ƒ„…†‡ˆ‰Š‹Œ‘2
’•–—˜Jrule.ShellCommand™2
š›œŸ ¡¢Jrule.ShellCommand£2
¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½Jrule.ShellCommand¾¿ÀÂ2
ÃJrule.ShellCommandÄ2
ÅÈÉÊËÌJrule.ShellCommandÍ2
Î2
ÏĞÓÔÕÖ×ØÙÚÛÜİŞßJrule.ShellCommandà2
áâãäåç2
èJrule.ShellCommandé2
êíîïğñJrule.ShellCommandò2
óôõö÷øùJrule.ShellCommandú2
û2
üışÿ‚ƒ„…†‡ˆ‰Š‹Œ‘’“”Jrule.ShellCommand•2
–—˜™š›œŸ ¡¢£¤¥¦¨2
©¬­®¯Jrule.ShellCommand°2
±²³´µ¶·¸¹Jrule.ShellCommandº2
»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕJrule.ShellCommandÖ×ØÚ2
ÛJrule.ShellCommandÜ2
İŞßâãäåæJrule.ShellCommandç2
è2
éêíîïğñòóôõö÷øùJrule.ShellCommandú2
ûüışÿ€Jrule.ShellCommand2
‚ƒ„…†‡ˆŠ2
‹Jrule.ShellCommandŒ2
‘’“”•–Jrule.ShellCommand—2
˜™š›œJrule.ShellCommandŸ2
 2
¡¢£¤§¨©ª«¬­®¯°±²³´µ¶·¸¹Jrule.ShellCommandº2
»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÍ2
ÎÑÒÓÔJrule.ShellCommandÕ2
Ö×ØÙÚÛÜİŞJrule.ShellCommandß2
àáâãäåæçèéêëìíîïğñòóôõö÷øùúJrule.ShellCommandûüıÿ2
€Jrule.ShellCommand2
‚…†‡ˆ‰Jrule.ShellCommandŠ2
‹2
Œ‘’“”•–—˜™š›œJrule.ShellCommand2
Ÿ ¡¢¤2
¥Jrule.ShellCommand¦2
§ª«¬­®Jrule.ShellCommand¯2
°±²³´µ¶Jrule.ShellCommand·2
¸2
¹º»¼¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑJrule.ShellCommandÒ2
ÓÔÕÖ×ØÙÚÛÜİŞßàáâãå2
æéêëìJrule.ShellCommandí2
îïğñòóôõöJrule.ShellCommand÷2
øùúûüışÿ€‚ƒ„…†‡ˆJrule.ShellCommand‰2
Š2
‹Œ‘’“”•–—˜™›2
œ¡Jrule.ShellCommand¢2
£¤¥¦§Jrule.ShellCommand¨2
©ª«¬­®¯°±²³´µ¶·¸¹Jrule.ShellCommandº2
Jrule.ShellWrapper½Jrule.ShellWrapper¾¿ÀÁJrule.ShellWrapperÂ2
ÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚJrule.ShellCommandÛ2
Jrule.ShellAssignmentŞßJrule.ShellAssignmentàáJrule.ShellAssignmentâãäåæJrule.ShellAssignmentçèéêëìíîïğñòóôõö÷øùúûüışÿJrule.ShellCommand€‚„2
…Jrule.ShellCommand†2
‡Š‹ŒJrule.ShellCommand2
2
‘’•–—˜™š›œŸ ¡Jrule.ShellCommand¢2
£¤¥¦§©2
ªJrule.ShellCommand«2
¬¯°±²³Jrule.ShellCommand´2
µ¶·¸¹º»Jrule.ShellCommand¼2
½2
¾¿ÀÁÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖJrule.ShellCommand×2
ØÙÚÛÜİŞßàáâãäåæçèê2
ëîïğñJrule.ShellCommandò2
óôõö÷øùúûJrule.ShellCommandü2
ışÿ€‚ƒ„…†‡ˆ‰Š‹ŒJrule.ShellCommand2
2
‘”•–—˜™š›œ 2
¡¢£¦Jrule.ShellCommand§2
¨©ª«¬Jrule.ShellCommand­2
®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑ"Ä|Ñ2¾|_&&_Ğ2Ë_||_=29_==_*
"
event
event_type2command.execƒ2_&&_622_==_*
"
eventsource_type
2otel?2;_==_
*
	"
event
event_type2command.resultâzĞJÜz
command"
shell_commands@result"É *5Ì20@not_strictly_falseË2!_Ê"	
@result2áyÎ2Ûy_||_Í"	
@resultÂyş2¼y_||_ĞEù2ÊE_||_£3Ô23_||_´"¼2®"_&&_J2F
*
"	
commandnamematches 2(?i)^(kubectl|oc)(\.exe)?$Ù!»JÓ!
i824lists.range%2!
*
"	
commandargvsize@result"´ *5·20@not_strictly_false¶2!_µ"	
@result2º ¹2´ _||_¸"	
@result› 2• _&&_¢32_&&_2_>_"
i ø 2ó!_ì2Jç
arg7#23
"*
!"	
commandargvslice$%"
i@result"+ *2.2.@not_strictly_false-2!_,"	
@result2S02O_||_/"	
@result8)24
	("
argmatches*2(?i)^(--help|--version)$:1"	
@resultç³2á_&&_»2µ_||_—Ç2‘_||_Öz2Ñ_&&_O82K
.62*_[_]5*
4"	
commandargv7"
imatches92
(?i)^exec$÷yJò
target8;24lists.range%>2!
=*
<"	
commandargvsize@result"r *2u2.@not_strictly_falset2!_s"	
@result2Ùw2Ô_||_v"	
@result¼a2·_&&_‡K2‚_&&_ B2_>_A"
targetC"
iXD2T!_NI2J
3G2/_[_]F*
E"	
commandargvH"
target
startsWithJ2-¤q2Ÿ_&&_‘L2Œ!_…`J€
argPO2L
N*
M"	
commandargvsliceQ2_+_P"
iRS"
target@result"Y *2\2.@not_strictly_false[2!_Z"	
@result2S^2O_||_]"	
@result8W24
	V"
argmatchesX2(?i)^(--help|--version)$:_"	
@result‚b2ı!_öp2ñ_&&_3d2/_>_c"
targetf2_+_e"
ig³n2®
Fj2B_[_]i*
h"	
commandargvl2_-_k"
targetmmatches[oW2U(?i)^(-c|--container|-f|--filename|--pod-running-timeout|--profile|--profile-output)$:x"	
@result¯Æ2©_&&_£…2_&&_O2K
.}2*_[_]|*
{"	
commandargv~"
imatches€2	(?i)^rsh$Dƒ2?
‚*
"	
commandnamematches„2(?i)^oc(\.exe)?$úÅJô
target<‡27lists.range(Š2#
‰*
ˆ"	
commandargvsize@result"¾ *5Á20@not_strictly_falseÀ2!_¿"	
@result2ÒÃ2Ì_||_Â"	
@result³­2­_&&_’—2Œ_&&_#2_>_"
target"
i_2Z!_T•2O
7“22_[_]’*
‘"	
commandargv”"
target
startsWith–2-½2‰_&&_¤˜2!_—¬J‘
argW›2R
š*
™"	
commandargvslice2_+_œ"
iŸ"
target@result"¥ *5¨20@not_strictly_false§2!_¦"	
@result2Xª2S_||_©"	
@result;£26

¢"
argmatches¤2(?i)^(--help|--version)$:«"	
@resultÙ®2Ó!_Ì¼2Æ_&&_8°23_>_¯"
target²2_+_±"
i³ƒº2~
L¶2G_[_]µ*
´"	
commandargv"¸2_-_·"
target¹matches%» 2(?i)^(-c|--container|--shell)$:Ä"	
@result’2Œ_&&_VÌ2Q
2Ê2-_[_]É*
È"	
commandargvË"
imatchesÍ2(?i)^debug$«ŒJ¥
target<Ï27lists.range(Ò2#
Ñ*
Ğ"	
commandargvsize@result"… *5ˆ20@not_strictly_false‡2!_†"	
@result2ƒŠ2ı_||_‰"	
@resultäô2Ş_&&_™Ş2“_&&_#Ö2_>_Õ"
target×"
ifÜ2a
7Ú22_[_]Ù*
Ø"	
commandargvÛ"
targetmatchesİ2(?i)^(node|pod)/[^/]+$¹„2³_&&_¤ß2!_—óJ‘
argWâ2R
á*
à"	
commandargvsliceä2_+_ã"
iåæ"
target@result"ì *5ï20@not_strictly_falseî2!_í"	
@result2Xñ2S_||_ğ"	
@result;ê26

é"
argmatchesë2(?i)^(--help|--version)$:ò"	
@resultƒõ2ı!_öƒ2ğ_&&_8÷23_>_ö"
targetù2_+_ø"
iú­2§
Lı2G_[_]ü*
û"	
commandargv"ÿ2_-_ş"
target€matchesN‚I2G(?i)^(--copy-to|-c|--container|--image|--profile|--set-image|--target)$:‹"	
@resultš²J”
j‘2lists.range’"
i@result"¬**®2%@not_strictly_false­"	
@result2¢°2œ_&&_¯"	
@resultƒ«2ı_||_|2w_||_–2_==_•"
j— Oœ2J
2š2-_[_]™*
˜"	
commandargv›"
j
startsWith2-öª2ğ_&&_ 2_>_Ÿ"
j¡È¨2Â
G¤2B_[_]£*
¢"	
commandargv¦2_-_¥"
j§matchesí©ç2ä(?i)^(-n|--namespace|--context|--cluster|--user|--kubeconfig|--server|--request-timeout|--as|--as-group|--token|--certificate-authority|--client-certificate|--client-key|--tls-server-name|--cache-dir|--profile|--profile-output)$:±"	
@result:º"	
@resultİÓ2×_&&_H¿2C
¾*
½"	
commandnamematchesÀ2(?i)^crictl(\.exe)?$„ÒJş
i<Â27lists.range(Å2#
Ä*
Ã"	
commandargvsize@result"Ë *5Î20@not_strictly_falseÍ2!_Ì"	
@result2áĞ2Û_||_Ï"	
@resultÂ¦2¼_&&_å2—_&&_·Ş2±_&&_É2_>_È"
iÊ ‰Ë2ƒ!_üİJö
arg<Î27
Í*
Ì"	
commandargvsliceÏĞ"
i@result"Ö *5Ù20@not_strictly_falseØ2!_×"	
@result2XÛ2S_||_Ú"	
@result;Ô26

Ó"
argmatchesÕ2(?i)^(--help|--version)$:Ü"	
@resultUã2P
2á2-_[_]à*
ß"	
commandargvâ"
imatchesä2
(?i)^exec$“Ê2_&&_ù¥Jó
target<ç27lists.range(ê2#
é*
è"	
commandargvsize@result" *5¡20@not_strictly_false 2!_Ÿ"	
@result2Ñ£2Ë_||_¢"	
@result²2¬_&&_’÷2Œ_&&_#î2_>_í"
targetï"
i_ğ2Z!_Tõ2O
7ó22_[_]ò*
ñ"	
commandargvô"
target
startsWithö2-2ˆ_&&_¤ø2!_—ŒJ‘
argWû2R
ú*
ù"	
commandargvsliceı2_+_ü"
işÿ"
target@result"… *5ˆ20@not_strictly_false‡2!_†"	
@result2XŠ2S_||_‰"	
@result;ƒ26

‚"
argmatches„2(?i)^(--help|--version)$:‹"	
@resultØ2Ò!_Ëœ2Å_&&_823_>_"
target’2_+_‘"
i“‚š2}
L–2G_[_]•*
”"	
commandargv"˜2_-_—"
target™matches$›2(?i)^(--cwd|--env|--exec-id)$:¤"	
@resultˆÉJ‚
j¨2lists.range©"
i@result"Ã**Å2%@not_strictly_falseÄ"	
@result2Ç2Š_&&_Æ"	
@resultñÂ2ë_||_|µ2w_||_­2_==_¬"
j® O³2J
2±2-_[_]°*
¯"	
commandargv²"
j
startsWith´2-äÁ2Ş_&&_·2_>_¶"
j¸¶¿2°
G»2B_[_]º*
¹"	
commandargv½2_-_¼"
j¾matches\ÀW2U(?i)^(-r|--runtime-endpoint|-i|--image-endpoint|-t|--timeout|--pull-image-on-create)$:È"	
@result:Ñ"	
@result›ø2•_&&_E×2@
Ö*
Õ"	
commandnamematchesØ2(?i)^ctr(\.exe)?$Å÷J¿
iQÚ2Llists.range=Ş28_-_(İ2#
Ü*
Û"	
commandargvsizeß@result"ğ *5ó20@not_strictly_falseò2!_ñ"	
@result2õ2‡_||_ô"	
@resultîˆ2è_&&_Ÿÿ2™_&&_·ø2±_&&_ã2_>_â"
iä ‰å2ƒ!_ü÷Jö
arg<è27
ç*
æ"	
commandargvsliceéê"
i@result"ğ *5ó20@not_strictly_falseò2!_ñ"	
@result2Xõ2S_||_ô"	
@result;î26

í"
argmatchesï2(?i)^(--help|--version)$:ö"	
@resultWı2R
2û2-_[_]ú*
ù"	
commandargvü"
imatchesş2(?i)^tasks?$½ï2·_&&_¹Ë2³_&&_j†2e
G‚2B_[_]*
€"	
commandargv„2_+_ƒ"
i…matches‡2
(?i)^exec$¾ÊJ¸
target<Š27lists.range(2#
Œ*
‹"	
commandargvsize@result"Ã *5Æ20@not_strictly_falseÅ2!_Ä"	
@result2–È2_||_Ç"	
@result÷²2ñ_&&_§œ2¡_&&_8‘23_>_"
target“2_+_’"
i”_•2Z!_Tš2O
7˜22_[_]—*
–"	
commandargv™"
target
startsWith›2-¾Â2¸_&&_¤2!_—±J‘
argW 2R
Ÿ*
"	
commandargvslice¢2_+_¡"
i£¤"
target@result"ª *5­20@not_strictly_false¬2!_«"	
@result2X¯2S_||_®"	
@result;¨26

§"
argmatches©2(?i)^(--help|--version)$:°"	
@resultˆ³2‚!_ûÁ2õ_&&_8µ23_>_´"
target·2_+_¶"
i¸²¿2¬
L»2G_[_]º*
¹"	
commandargv"½2_-_¼"
target¾matchesSÀN2L(?i)^(--cwd|--env|--env-file|--exec-id|--groups|--log-uri|--process|--user)$:É"	
@resultòîJì
jÍ2lists.rangeÎ"
i@result"è**ê2%@not_strictly_falseé"	
@result2úì2ô_&&_ë"	
@resultÛç2Õ_||_|Ú2w_||_Ò2_==_Ñ"
jÓ OØ2J
2Ö2-_[_]Õ*
Ô"	
commandargv×"
j
startsWithÙ2-Îæ2È_&&_Ü2_>_Û"
jİ ä2š
Gà2B_[_]ß*
Ş"	
commandargvâ2_-_á"
jãmatchesFåA2?(?i)^(-a|--address|-n|--namespace|--timeout|--connect-timeout)$:í"	
@result:ö"	
@resultà3È2Ú3_||_¡ı2›_&&_Hü2C
û*
ú"	
commandnamematchesı2(?i)^docker(\.exe)?$ÈüJÂ
i<ÿ27lists.range(‚2#
*
€"	
commandargvsize@result"õ *5ø20@not_strictly_false÷2!_ö"	
@result2¥ú2Ÿ_||_ù"	
@result†ã2€_&&_¢2—_&&_·›2±_&&_†2_>_…"
i‡ ‰ˆ2ƒ!_üšJö
arg<‹27
Š*
‰"	
commandargvsliceŒ"
i@result"“ *5–20@not_strictly_false•2!_”"	
@result2X˜2S_||_—"	
@result;‘26

"
argmatches’2(?i)^(--help|--version)$:™"	
@resultU 2P
22-_[_]*
œ"	
commandargvŸ"
imatches¡2
(?i)^exec$×ô2Ñ_&&_’‡2Œ_&&_âJ—
target<¤27lists.range(§2#
¦*
¥"	
commandargvsize@result"Û *5Ş20@not_strictly_falseİ2!_Ü"	
@result2õà2ï_||_ß"	
@resultÖÊ2Ğ_&&_’´2Œ_&&_#«2_>_ª"
target¬"
i_­2Z!_T²2O
7°22_[_]¯*
®"	
commandargv±"
target
startsWith³2-²Ú2¬_&&_¤µ2!_—ÉJ‘
argW¸2R
·*
¶"	
commandargvsliceº2_+_¹"
i»¼"
target@result"Â *5Å20@not_strictly_falseÄ2!_Ã"	
@result2XÇ2S_||_Æ"	
@result;À26

¿"
argmatchesÁ2(?i)^(--help|--version)$:È"	
@resultüË2ö!_ïÙ2é_&&_8Í23_>_Ì"
targetÏ2_+_Î"
iĞ¦×2 
LÓ2G_[_]Ò*
Ñ"	
commandargv"Õ2_-_Ô"
targetÖmatchesGØB2@(?i)^(-e|--env|--env-file|--detach-keys|-u|--user|-w|--workdir)$:á"	
@resultã†Jİ
jå2lists.rangeæ"
i@result"€**‚2%@not_strictly_false"	
@result2ë„2å_&&_ƒ"	
@resultÌÿ2Æ_||_|ò2w_||_ê2_==_é"
jë Oğ2J
2î2-_[_]í*
ì"	
commandargvï"
j
startsWithñ2-¿ş2¹_&&_ô2_>_ó"
jõ‘ü2‹
Gø2B_[_]÷*
ö"	
commandargvú2_-_ù"
jûmatches7ı220(?i)^(-H|--host|--config|--context|--log-level)$:…"	
@result³Ù2­_||_­¸2§_||_„™Jş
arg<Š27
‰*
ˆ"	
commandargvslice‹Œ"
i@result"’ *5•20@not_strictly_false”2!_“"	
@result2`—2[_||_–"	
@resultC2>

"
argmatches'‘"2 (?i)^(-H|--host)=(ssh|tcp)://.+$:˜"	
@result—·J‘
j1›2,lists.range2_-_œ"
i@result"° *5³20@not_strictly_false²2!_±"	
@result2ÿµ2ù_||_´"	
@resultà¯2Ú_&&_\¥2W
2£2-_[_]¢*
¡"	
commandargv¤"
jmatches¦2(?i)^(-H|--host)$t­2o
G©2B_[_]¨*
§"	
commandargv«2_+_ª"
j¬matches®2(?i)^(ssh|tcp)://.+$:¶"	
@resultôó2î_||_ÜØJÖ
wrapperº*
¹"	
commandwrappers@result"Ñ *5Ô20@not_strictly_falseÓ2!_Ò"	
@result2ĞÖ2Ê_||_Õ"	
@result±Ğ2«_&&_=¿28
¾*
½"	
wrappernamematchesÀ2	(?i)^env$ãÏJİ
argÂ*
Á"	
wrapperargv@result"È *5Ë20@not_strictly_falseÊ2!_É"	
@result2`Í2[_||_Ì"	
@resultCÆ2>

Å"
argmatches'Ç"2 (?i)^DOCKER_HOST=(ssh|tcp)://.+$:Î"	
@result:×"	
@result†òJ€

assignment"Û*
Ú"	
commandassignments@result"ë *5î20@not_strictly_falseí2!_ì"	
@result2ôğ2î_||_ï"	
@resultÕê2Ï_&&_yå2t_&&_+Ş2&!_ à*
ß"

assignmentappend?ã2:_==_â*
á"

assignmentnameä2DOCKER_HOSTLè2G
ç*
æ"

assignmentvaluematchesé2(?i)^(ssh|tcp)://.+$:ñ"	
@result:û"	
@result­Ç2§_&&_H2C
€*
ÿ"	
commandnamematches‚2(?i)^podman(\.exe)?$ÔÆJÎ
i<„27lists.range(‡2#
†*
…"	
commandargvsize@result"¿ *5Â20@not_strictly_falseÁ2!_À"	
@result2±Ä2«_||_Ã"	
@result’è2Œ_&&_§2—_&&_· 2±_&&_‹2_>_Š"
iŒ ‰2ƒ!_üŸJö
arg<27
*
"	
commandargvslice‘’"
i@result"˜ *5›20@not_strictly_falseš2!_™"	
@result2X2S_||_œ"	
@result;–26

•"
argmatches—2(?i)^(--help|--version)$:"	
@resultU¥2P
2£2-_[_]¢*
¡"	
commandargv¤"
imatches¦2
(?i)^exec$ã¾2İ_&&_°Œ2ª_&&_ºçJ´
target<©27lists.range(¬2#
«*
ª"	
commandargvsize@result"à *5ã20@not_strictly_falseâ2!_á"	
@result2’å2Œ_||_ä"	
@resultóÏ2í_&&_’¹2Œ_&&_#°2_>_¯"
target±"
i_²2Z!_T·2O
7µ22_[_]´*
³"	
commandargv¶"
target
startsWith¸2-Ïß2É_&&_¤º2!_—ÎJ‘
argW½2R
¼*
»"	
commandargvslice¿2_+_¾"
iÀÁ"
target@result"Ç *5Ê20@not_strictly_falseÉ2!_È"	
@result2XÌ2S_||_Ë"	
@result;Å26

Ä"
argmatchesÆ2(?i)^(--help|--version)$:Í"	
@result™Ğ2“!_ŒŞ2†_&&_8Ò23_>_Ñ"
targetÔ2_+_Ó"
iÕÃÜ2½
LØ2G_[_]×*
Ö"	
commandargv"Ú2_-_Ù"
targetÛmatchesdİ_2](?i)^(-e|--env|--env-file|--detach-keys|--preserve-fd|--preserve-fds|-u|--user|-w|--workdir)$:æ"	
@resultä‹JŞ
jê2lists.rangeë"
i@result"…**‡2%@not_strictly_false†"	
@result2ì‰2æ_&&_ˆ"	
@resultÍ„2Ç_||_|÷2w_||_ï2_==_î"
jğ Oõ2J
2ó2-_[_]ò*
ñ"	
commandargvô"
j
startsWithö2-Àƒ2º_&&_ù2_>_ø"
jú’2Œ
Gı2B_[_]ü*
û"	
commandargvÿ2_-_ş"
j€matches8‚321(?i)^(--url|--connection|--identity|--log-level)$:Š"	
@result¡½2›_||_şJø
arg<27
*
"	
commandargvslice‘"
i@result"— *5š20@not_strictly_false™2!_˜"	
@result2Zœ2U_||_›"	
@result=•28

”"
argmatches!–2(?i)^--url=(ssh|tcp)://.+$:"	
@result‘¼J‹
j1 2,lists.range¢2_-_¡"
i£@result"µ *5¸20@not_strictly_false·2!_¶"	
@result2ùº2ó_||_¹"	
@resultÚ´2Ô_&&_Vª2Q
2¨2-_[_]§*
¦"	
commandargv©"
jmatches«2(?i)^--url$t²2o
G®2B_[_]­*
¬"	
commandargv°2_+_¯"
j±matches³2(?i)^(ssh|tcp)://.+$:»"	
@result:Å"	
@result:Ï"	
@result*ˆBYnumbat:cel-env-v1:sha256:b8dbfa907058f0ad41d1c0c0e780fb7a0094a860d35d79f39361d59d39dea8edq”Ïşåí÷ªäş³î¤µÄäìú†“Ï†ÀÚ	Ê	€
‘
 
À
‘Ÿ«¸Âö°ÊË’¡Á»ÉÕßê†˜ÃÍàîø€†‘Æõ„Ü‹Á×ˆ¿ñş‰¥ñû†¢´ßéüû…“šĞƒ’ê›Î„Ï†¸ÅĞìçñü˜ ª Õ ß ò Û!å!í!ó!ú!ş!³"â"ñ"É#ø#®$Ä$õ$¬%Ş%ë%ö%’&'‹'–'²'Ä'ï'ù'Œ(æ(ğ(û(ƒ)°)ê)÷)œ*Ö*”+¡+Ê+ù+Í,Ú,‰-©-×-’.œ.¤.ª.±.µ.ê.™/¨/€0¯0å0û0¬1ã1•2¢2­2É2Õ3ß3ê3†4˜4Ã4Í4à4»5Å5Ğ5Ø5…6¹6Æ6ë6Ÿ7İ7ç7ï7õ7ù7û7"""""("-":"="	G"
L"X"["D"$"q"˜"Ÿ"¬"­"Ş"ß"æ"ğ"„"†"ˆ" “"!”""›"#¦"$§"%ª"(¹")Ä"*Å"+³",³"-³".³"/³"0³"1³"2³"3Š"4"5ˆ"6"7"8˜"9™";¿"<À"=Ç">Ñ"Ağ"B÷"Cù"DŠ"E‹"F’"G—"H˜"Iª"J«"Kû"L¿"MÀ"NÇ"OÒ"PÓ"QÕ"R×"SÚ"Vü"W‡"Xˆ"Yè"Zè"[è"\è"]è"^è"_è"`è"a°"bÁ"cÒ"dÙ"eÛ"fİ"gß"hò"iù"jş"kÿ"l†"mˆ"n’"o“"pá"q²"rÛ"sÛ"tÛ"uÛ"vÛ"wÛ"xÛ"yÛ"z§"{§"|®"}³"~´"¾"€¿"Ù"‚à"ƒí"„î"…Ì"‡›"ˆœ"‰£"Š­"Ì"Ó"Õ"æ"‘ç"’î"“ó"”ô"•†	"–‡	"—×"˜›	"™œ	"š£	"›®	"œ¯	"±	"³	"Ÿ¶	"¢Ø	"£ã	"¤ä	"¥Ä	"¦Ä	"§Ä	"¨Ä	"©Ä	"ªÄ	"«Ä	"¬Ä	"­Œ	"®
"¯®
"°µ
"±·
"²¹
"³»
"´Î
"µÕ
"¶Ú
"·Û
"¸â
"¹ä
"ºî
"»ï
"¼½
"½
"¾·"¿·"À·"Á·"Â·"Ã·"Ä·"Å·"Æƒ"Ç"ÈÌ"ÉÓ"ÊØ"ËÙ"Ìã"Íä"Ï‹"ĞŒ"Ñ“"Ò"Õ¼"ÖÃ"×Å"ØÖ"Ùİ"Úâ"Ûã"Üò"İó"ŞÇ"ßœ"à"á¤"â¯"ã°"ä²"å´"æ·"éÙ"êä"ëå"ìÅ"íÅ"îÅ"ïÅ"ğÅ"ñÅ"òÅ"óÅ"ô"õ"ö¯"÷¶"ø¸"ùº"ú¼"ûÏ"üÖ"ıÛ"şÜ"ÿã"€å"ï"‚ğ"ƒ¾"„"…§"†§"‡§"ˆ§"‰§"Š§"‹§"Œ§"ó"µ"â"‘û"’ü"•"–"—“"˜ "™§"š¬"›­"œº"»"•"Ÿ×" Ù"¡Û"¢ê"£ñ"¤ö"¥÷"¦ù"§û"¨…"©†"ªİ"«À"¬‚"­‚"®‚"¯‚"°‚"±‚"²‚"³ç"´ú"µú"¶ú"·ú"¸ú"¹ú"ºú"»ú"¼Ì"½•"¾œ"¿©"Àª"ÂÕ"ÃÖ"Äİ"Åç"Èû"Éı"Êÿ"ËŠ"Ì‹"Í’"Î"Ï"Ğ¡"Ó°"Ô»"Õ¼"Öª"×ª"Øª"Ùª"Úª"Ûª"Üª"İª"Ş"ßâ"àé"áî"âï"ãù"äú"åÙ"çœ"è"é¤"ê®"íÉ"îĞ"ïÒ"ğß"ñà"òç"óì"ôí"õÿ"ö€"÷Ô"ø"ù‘"ú˜"û£"ü¤"ı¦"ş¨"ÿ«"‚É"ƒÔ"„Õ"…¹"†¹"‡¹"ˆ¹"‰¹"Š¹"‹¹"Œ¹"…"†"“"š"‘œ"’"“ "”¯"•¶"–»"—¼"˜Ã"™Å"šÏ"›Ğ"œ¢"û"¸"Ÿ¸" ¸"¡¸"¢¸"£¸"¤¸"¥¸"¦ˆ"¨—"©˜"¬ª"­¬"®¯"¯¼"°Ã"±È"²É"³Ö"´×"µ±"¶ó"·õ"¸÷"¹†"º"»’"¼“"½•"¾—"¿¡"À¢"Áù"ÂÜ"Ã"Ä"Å"Æ"Ç"È"É"Êƒ"Ëñ"Ìñ"Íñ"Îñ"Ïñ"Ğñ"Ññ"Òñ"ÓÃ"ÔŠ"Õ¢"Ö©"×¶"Ø·"Úß"Ûà"Üç"İñ"Şô"ßö"â‰"ã‹"ä"å˜"æ™"ç "è«"é¬"ê¯"í¾"îÉ"ïÊ"ğ¸"ñ¸"ò¸"ó¸"ô¸"õ¸"ö¸"÷¸"ø"ùğ"ú÷"ûü"üı"ı‡"şˆ"ÿç"€¡"¨"‚­"ƒ®"„°"…²"†¼"‡½"ˆ˜"Šß"‹à"Œç"ñ"Œ"‘“"’•"“—"”™"•¦"–§"—®"˜³"™´"šÆ"›Ç"œ›"×"Ø"Ÿß" ê"¡ë"¢í"£ï"¤ò"§"¨›"©œ"ª€"«€"¬€"­€"®€"¯€"°€"±€"²Ì"³Í"´Ú"µá"¶ã"·å"¸ç"¹ö"ºı"»‚"¼ƒ"½Š"¾Œ"¿–"À—"Áé"ÂÂ"Ãû"Äû"Åû"Æû"Çû"Èû"Éû"Êû"ËË"Í "Î "Ñ  "Ò¢ "Ó¥ "Ô² "Õ¹ "Ö¾ "×¿ "ØÌ "ÙÍ "Ú§ "Ûé "Üë "İí "Şü "ßƒ!"àˆ!"á‰!"â‹!"ã!"ä—!"å˜!"æï "çÒ "è” "é” "ê” "ë” "ì” "í” "î” "ïù"ğÿ"ñÿ"òÿ"óÿ"ôÿ"õÿ"öÿ"÷ÿ"øÍ"ù—"ú‚""û‰""ü–""ı—""ÿÂ""€Ã""Ê""‚Ô""…è""†ê""‡ì""ˆ÷""‰ø""Šÿ""‹Š#"Œ‹#"#"#"‘¨#"’©#"“—#"”—#"•—#"–—#"——#"˜—#"™—#"š—#"›î""œÏ#"Ö#"Û#"ŸÜ#" æ#"¡ç#"¢Æ#"¤‰$"¥Š$"¦‘$"§›$"ª¶$"«½$"¬¿$"­Ì$"®Í$"¯Ô$"°Ù$"±Ú$"²ì$"³í$"´Á$"µı$"¶ş$"·…%"¸%"¹‘%"º“%"»•%"¼˜%"¿¶%"ÀÁ%"ÁÂ%"Â¦%"Ã¦%"Ä¦%"Å¦%"Æ¦%"Ç¦%"È¦%"É¦%"Êò$"Ëó%"Ì€&"Í‡&"Î‰&"Ï‹&"Ğ&"Ñœ&"Ò£&"Ó¨&"Ô©&"Õ°&"Ö²&"×¼&"Ø½&"Ù&"Úè%"Û¥$"Ü¥$"İ¥$"Ş¥$"ß¥$"à¥$"á¥$"â¥$"ãõ#"å§'"æ¨'"éº'"ê¼'"ë¿'"ìÌ'"íÓ'"îØ'"ïÙ'"ğæ'"ñç'"òÁ'"óƒ("ô…("õ‡("ö–("÷("ø¢("ù£("ú¥("û§("ü±("ı²("ş‰("ÿì'"€®'"®'"‚®'"ƒ®'"„®'"…®'"†®'"‡“'"ˆ‹)"‰’)"Š)"‹)"Œ¡)"º)"Å)"‘Æ)"’ª)"“ª)"”ª)"•ª)"–ª)"—ª)"˜ª)"™ª)"›Š*"œ‹*"*"*"¡¦*"¢­*"£²*"¤³*"¥½*"¦¾*"§à*"¨ç*"©ì*"ªí*"«ï*"¬ñ*"­û*"®ü*"¯Ó*"°˜*"±˜*"²˜*"³˜*"´˜*"µ˜*"¶˜*"·˜*"¸ô)"¹©+"º°+"½Ô+"¾Û+"¿è+"Àé+"Áƒ,"ÂŠ,"Åœ,"Æ§,"Ç¨,"È–,"É–,"Ê–,"Ë–,"Ì–,"Í–,"Î–,"Ï–,"Ğö+"ÑÀ+"ÒÀ+"ÓÀ+"ÔÀ+"ÕÀ+"ÖÀ+"×À+"ØÀ+"Ù+"Úâ,"Ûé,"Ş“-"ß”-"à-"á³-"â½-"ãÃ-"äÆ-"å¦-"æá-"çë-"èù-"éú-"êÔ-"ëü,"ìü,"íü,"îü,"ïü,"ğü,"ñü,"òü,"ó×,"ôø("õŞ""öŞ""÷Ş""øŞ""ùŞ""úŞ""ûŞ""üŞ""ı°""ş÷!"ÿ¹."€À."Í."‚Î."„ù."…ú."†/"‡‹/"ŠŸ/"‹¡/"Œ£/"®/"¯/"¶/"Á/"‘Â/"’Å/"•Ô/"–ß/"—à/"˜Î/"™Î/"šÎ/"›Î/"œÎ/"Î/"Î/"ŸÎ/" ¥/"¡†0"¢0"£’0"¤“0"¥0"¦0"§ı/"©À0"ªÁ0"«È0"¬Ò0"¯í0"°ô0"±ö0"²ƒ1"³„1"´‹1"µ1"¶‘1"·£1"¸¤1"¹ø0"º´1"»µ1"¼¼1"½Ç1"¾È1"¿Ê1"ÀÌ1"ÁÏ1"Äí1"Åø1"Æù1"Çİ1"Èİ1"Éİ1"Êİ1"Ëİ1"Ìİ1"Íİ1"Îİ1"Ï©1"Ğª2"Ñ·2"Ò¾2"ÓÀ2"ÔÂ2"ÕÄ2"ÖÓ2"×Ú2"Øß2"Ùà2"Úç2"Ûé2"Üó2"İô2"ŞÆ2"ßŸ2"àÜ0"áÜ0"âÜ0"ãÜ0"äÜ0"åÜ0"æÜ0"çÜ0"è¬0"êû3"ëü3"î4"ï4"ğ“4"ñ 4"ò§4"ó¬4"ô­4"õº4"ö»4"÷•4"ø×4"ùÙ4"úÛ4"ûê4"üñ4"ıö4"ş÷4"ÿù4"€û4"…5"‚†5"ƒİ4"„À4"…‚4"†‚4"‡‚4"ˆ‚4"‰‚4"Š‚4"‹‚4"Œç3"à5"ç5"ò5"ó5"‘ö5"”6"•š6"–›6"—ÿ5"˜ÿ5"™ÿ5"šÿ5"›ÿ5"œÿ5"ÿ5"ÿ5" Ù6"¡Ú6"¢Ü6"£Ş6"¦õ6"§ü6"¨7"©‚7"ªŒ7"«7"¬©7"­°7"®µ7"¯¶7"°¸7"±º7"²Ä7"³Å7"´œ7"µç6"¶ç6"·ç6"¸ç6"¹ç6"ºç6"»ç6"¼ç6"½Ã6"¾Í5"¿•/"À•/"Á•/"Â•/"Ã•/"Ä•/"Å•/"Æ•/"Çç."È®."É†"Ê†"Ë†"Ì†"Í†"Î†"Ï†"Ğ†"Ñn